---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: nxos
namespace: cisco
readme: README.rst
repository: https://github.com/ansible-collections/nxos
version: 0.0.1
